INSERT INTO "categories" ("name") VALUES
    ('personal'),
    ('retail'),
    ('manufacturing'),
    ('healthcare'),
    ('financial services'),
    ('real estate'),
    ('technology'),
    ('hospitality'),
    ('education'),
    ('logistics'),
    ('construction'),
    ('agriculture'),
    ('automotive'),
    ('consulting'),
    ('wholesale'),
    ('energy');
