services:
  db:
    image: postgres:latest
    ports:
      - "8080:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemelater

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"     # http://localhost:9001/browser
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"    # Web UI at http://localhost:8025
      - "1025:1025"    # SMTP port (your services will send mail to this)
    restart: always

volumes:
  minio_data:
