package com.project.common.exceptions

enum class ErrorCode {
    ACCESS_DENIED,
    ACCOUNT_NOT_FOUND,
    ACCOUNT_LIMIT_REACHED,
    ACCOUNT_VERIFICATION_EXCEPTION,
    INVALID_CREDENTIALS,
    INVALID_ACCOUNT_TYPE,
    INVALID_AMOUNT,
    INVALID_FUNDS,
    INVALID_TRANSFER,
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    USER_ID_NOT_FOUND,
    INVALID_INPUT,
    INVALID_AGE,
    INTERNAL_SERVER_ERROR,
    UNAUTHORIZED
}